### ISSUE TITLE
Question: Morpheus tool et PlutoSDR

### ISSUE THREAD

**Issue by satfan52** [LamaBleu/plutoscripts#1]
Bonjour,

Je cherche a comprendre si avec l'image PlutoSDR  "custom" que vous avez crée avec tous ces outils et scripts, il est possible d'utiliser mon PlutoSDR  pour mesure la courbe de réponse en fréquence d'un DUT (filtre ou d'une antenne par exemple) 

Dans le release note il est indiqué  "Morpheus" tool, c'est pour ca que je pose la question ? Le programme émule t'il un Morpheus ? 

Ce que je cherche sur le net , c'est un programme qui permet d'utiliser mon PlutoSDR pour mesurer la réponse en fréquence d'un DUT. Si vous savez me mettre sur la bonne direction, je vous en serais reconnaissant car jusque a présent je n'ai pas trouvé.

Cordialement

**Comment by unixpunk** [comment]
Translate if needed or wait for LamaBleu to respond - This tool is MoRFeus tool, its to control this device: https://othernet.is/collections/outernet-product-catalog/products/morfeus-1

Hope that helps!

**Comment by satfan52** [comment]
Thanks I understand what this device (Morpheus) can do.  However, I still miss the point about the relevance of using the Morpheus device in combination with the PlutoSDR device as I think (?) it is inferred  [in this article published on RTL-SDR.com](https://www.rtl-sdr.com/new-custom-firmware-for-the-plutosdr-with-several-linux-sdr-programs-pre-installed/). As you can read, the PlutoSDR immage that is cited in this article includes the Morpheus tool and I wonder why ? Is the idea to use the Morpheus device as a down converter to extend the coverage of the PlutoSDR below 70 Mhz ? Can you clarify? Regards

**Comment by unixpunk** [comment]
If you combine this tool with some of the wrappers/front-ends or other controlling applications for the MoRFeus, then you could certainly do a spectrum sweep with it.  You could use the signal generation function with a tap or other device to measure the swr of an antenna.  To your point, it would allow you to access the 30-70mhz range using it as an up-converter.  It would also allow you to add a bias-t function to PlutoSDR since it does not have the ability to provide 5v on the antenna port.  i.e., it could be used to power a SpyVerter to then give you access to the entire HF band as well.  Use your imagination.  :)  Hope that helps!

**Comment by LamaBleu** [comment]
Hi @saftan52
First: many thanks to @unixpunk for initial answering. He knows I'm off during February, that's why I'm long to reply.  BTW @unixpunk I feel good, turning on computer for the first time since I left France. I'm in Kourou space center today.
The idea was to adapt initial version of moRFeus_GUI (https://github.com/LamaBleu/moRFeus_GUI) I wrote last year, to be used with pluto instead of classic RTL-SDR, to extend freq range. However moRFeus_GUI needs GQRX to get signal level ... I will perhaps (or not) work again on moRFeus_GUI, to use SoapySDR and acquire signal level without GQRX.
And the idea was NOT to work below 70 MHz !
It's probably an easy task to adapt moRFeus_GUI however I focused on DATV these last weeks.

In french : désolé pour la réponse tardive, j'ai bien compris votre question, et en l'état non ce n'est pas possible, mais la tâche n'est pas bien compliquée. Je suis prêt à m'y coller à partir de mi-mars s'il y a du monde intéressé.
Pour l'instant je suis plutôt en mode hors-connexion, et peu de réseau d'où je suis. Salutations depuis la Guyane. On en reparle en début mars en fonction de vos besoins?

**Comment by satfan52** [comment]
Bonsoir,

Merci pour les deux réponses en Anglais er en Français. J ai bien compris
maintenant. Oui on en reparle en Mars.

Çela serait vraiment extraordinaire si il y avait une application qui
permet d utiliser le pluto SDR pour mesurer la réponse en fréquence d un
filtre ou d une antenne par exemple en utilisant un coupleur directionnel
externe. Le plutôt peux le faire sans le Morpheus by the way, la see chose
que le Morpheus pourait apporter C est peux être de pouvoir couvrir le
segment de 0 à 70 Mhz non couvert par le PlutoSDR.

 J ai regrade partout sur le net et personne ne l à encore fait, il y a
juste un script Matlab, mais il faut une license très onéreuse. Je pense
que la difficulté C est de prévoir dans le programme une procédure de
calibration pour que la mesure de la réponse en fréquence soit précise. Le
top uktimr serait évidement de pouvoir mesurer l amplitude et la phase pour
faire un VNA 1 et peux être 2 port

Bon séjour à Kourou

Peter

**Comment by satfan52** [comment]
Je joins pour référence et historique quelques lien vers l'application open source "VNA" (Vector Network Analyser)  développée pour le red-pitaya pour fonctionner entre 0 et 60 Mhz et qui utilise lui aussi un Zyncq 7010 (mais deux DAC et deux ADC a la place d'un transceiver AD9363/4). Ce qui serais génial serais d'avoir quelque chose d' équivalent pour le Pluto mais qui fonctionne entre 70mhz et 6 Ghz.

http://pavel-demin.github.io/red-pitaya-notes/vna/

et

https://github.com/pavel-demin/red-pitaya-notes/issues/808

et

https://github.com/pavel-demin/red-pitaya-notes/issues/774

voir aussi la discussion VNA/SNA sur le site the analogue device

https://ez.analog.com/university-program/f/q-a/101880/can-adam-pluto-be-used-as-cheap-experimental-scalar-or-vector-network-analyser

Pour fournir un tableau complet du sujet VNA/SNA, il me faut ajouter que le [NWT6000 developé par BG7TBL](http://www.mikrofale.iq24.pl/podglad_posta.asp?id_komentarza=2306394) et que je possède aussi me permet a faible cout (250 euros) de faire des scan de réponse en fréquence entre 25 Mhz et 6 Ghz de façon relativement satisfaisante pour une utilisation amateur (avec une dynamique entre 80 et 60 dB selon la fréquence). Mais c 'est très basique et ce device n'est pas un "SDR" comme le Pluto  (donc moins précis, pas toujours très linaire et trés dificile a calibrer) et surtout,  cela n'est pas un VNA comme le red pitayaya mais un SNA. L' interfaxe utilisateur n'est pas franchement performante et n'évolue plus du tout, elle n'est meme plus maintenue

**Comment by satfan52** [comment]
It seems the desired functionality will be available in the Scopy app that is currently under development for the ADALM 2000 and will be ported to the ADALM Pluto at a later stage
https://wiki.analog.com/university/tools/m2k/scopy

**Comment by unixpunk** [comment]
@satfan52 Thanks for sharing!  This app won't run directly on the Pluto itself, from what I gather - if you find something that can be run directly on the Pluto itself, please share that here or on my PlutoWeb repo as well.  I would like to implement an SNA/VNA that can be used directly from a web browser like most other things in my PlutoWeb firmware.  I may resort to some iio_* scripting or finding some C example (which I have already) to accomplish this via the cmd line.  If you or someone you know has the knowledge to assist with this, I can't pay but I can provide credits/attributes.  :)

**Comment by satfan52** [comment]
You are welcome! Ok I did not realize your goal was to run a server on the
Pluto itself and then use a webclient as the access method for the
ebd-user. This means that an external USB based Ethernet interface must be
added to the Pluto, not an issue of course as it is supported natively by
the Pluto

I think the author of the VNA application for the red pitaya is probably
the person you are looking for. Though of course I have no idea if he is
willing to invest time for this. I would suggest you contact Pavel Demin
directly to find out how he can or cannot guide  you with this. I will be
posting the link to his VNA repository later here. The red pitaya and the
Pluto share the same Zynq10 processor through the red pitaya board has much
more memory than the Pluto.
The front end  and the back end to the Zynq10 on the red pitaya are a pair
of ADCs (for the 2 receiving channels) and DAQs (for the 2 transmitting
channels) whereas the Pluto uses an AD9363 transceiver and only has one TX
and one RX channel (instead of 2 RX+2TX for the redpitaya) . The client is
not a web interface put a python script. The server runs on the redpitaya.
Despite these interferences it seems to me that his VNA client server
application could be ported to the Pluto environment as his VNA client
server aplication (I think but I am not sure) uses only 1 receiver and 1
transceiver. He mentioned it himself by the way in one of the threats on
his github page.

I ll post the links later

**Comment by satfan52** [comment]
Key links in relation to my previous post/messages

http://pavel-demin.github.io/red-pitaya-notes/vna/

analogdevicesinc/iio-oscilloscope#143 (comment)

**Comment by unixpunk** [comment]
Thanks again!  I have also been following this a bit too in hopes it may work someday.  I will ask him what he thinks the effort is, but does sound promising considering the architecture they've designed for their tool.

**Comment by satfan52** [comment]
See the discussion around issue

https://github.com/pavel-demin/red-pitaya-notes/issues/688

and the statement of the author of the red pitaya VNA client server app in
relation to porting it to the  Pluto

 "

There is also ADALM-PLUTO
<http://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/adalm-pluto.html>.
Like Red Pitaya, it's based on the Xilinx Zynq chip. I think that my VNA
application can be easily ported to this board.

"

**Comment by unixpunk** [comment]
Thanks, yes, in another thread he basically offered me to port it, lol...  :)  We'll see.  I have an issue open on it in the PlutoWeb repo https://github.com/unixpunk/PlutoWeb/issues/50

**Comment by LamaBleu** [comment]
Hi @satfan52 @unixpunk . Sorry for my late answer.. Slowly back to pluto life.
Thanks for the links, very instructive !
Yes saftan we are more considering implementing this feature as native on the pluto, then you just have to display a web page, or download few files to get the result. That's why GNUplot is included on the firmware.
And I don't plan to work below 70MHz sorry.
 
After a first look to pavel's github, I thought it was not possible/too complex to port the VNA app.
We have limit on flash memory; and there are lot of dependencies.
As said by unixpunk we yet have few bricks to start something cool. However ...I'm not sure using the Pluto as generator is a good idea even if it looks simpler : I don't think the signal level is linear across the spectrum (TBC).
I more inclined to use moRFeus as signal generator : we have remote control over moRFeus and can even deport it to another location/computer. Perhaps I'm wrong !

I keep the idea in background and will let you informed. Need to write scripts which may help to resume this little project.
Things may change quickly: I'm sure we will have this kind of app very soon ! scopy or another one.

**Comment by satfan52** [comment]
OK thanks. Clear

**Comment by LamaBleu** [comment]
Hey guys, seems someone worked a lot on similar project last month.
I will have a look, but looks just perfect. I'm too busy now but we have to contact Kalvin ASAP ;) 
http://www.eevblog.com/forum/rf-microwave/adalm-pluto-as-vhfuhf-spectrum-analyzer-and-a-tracking-generator/

**Comment by satfan52** [comment]
I read the threat, and apparently the main issue is the tuning delay, but
on the other hand if the bandwidth available is 56 Mhz t is quite good
already for making sna or vna rf measurements and I guess  only a limited
number of hops would be  required to swep 1ghz of bandwidth for instance. I
find hard to believe that the receiver and transmitter of the Pluto use
different lo with uncorrelated phases, that is  not really convenient for
digital communications

**Comment by LamaBleu** [comment]
This one recently released for Lime is very good. Based on SoapySDR. 
https://github.com/nepeee/limeSNA
Installed on my computer, performed a quick test after [some mods](https://drive.google.com/open?id=1joXlOKs7DluyMMRZ9Ap9r-rhG32R9dlo), can be ported to pluto.
However not functional at this moment. Hope to work on this next week-end.

**Comment by satfan52** [comment]
Super, looks promising indeed!

**Comment by LamaBleu** [comment]
Hi @satfan52  @unixpunk 
first plot today using pluto and limeSNA, however there is a lot to do. will keep you informed.
--> Worked on the RX side only, and getting frequent crashes `Erreur de segmentation (core dumped)`



![limesna2](https://user-images.githubusercontent.com/26578895/56524807-5a640380-654a-11e9-8852-9ad7da3edbf5.png)

**Comment by satfan52** [comment]
Hello,

Well it looks very encouraging! I will be happy to test your code and give
you feedback  at a later stage when you will ll be ready with the first
test version


I wonder if this code makes use of FGPA ressources of the Zynq7010 or not".
It does not really matter from an end user perspective of course but I am
just curious to find out .

If limeSDR code can be ported to Pluto (that is a nice surprise), then let
me also draw your attention on this experimental VNA  code  (as a possible
source of inspiration for future projects or at a much later stage, as an
upgrade of the SNA that you are currently developing  )

https://myriadrf.org/news/limesdr-made-simple-part-9-vna/

Thanks
Regards
Peter

**Comment by LamaBleu** [comment]
Regarding the title of this issue "pluto and moRFeus" : solved and closing.
 I will release very soon a miniSNA for pluto, using moRFeus as generator and adalm-pluto as receiver.

- a light version using bash, gnuplot and a specific tool I developed to replace rtl_power.
This version might be ported later as native to pluto.
![380-480](https://user-images.githubusercontent.com/26578895/56868041-5f630000-69ed-11e9-82bf-d2d498fa44bd.png)


- Another version based on [limeSNa](https://github.com/nepeee/limeSNA) from @nepeee , based on python, HTML and javascript, initially written for limeSDR.

![limesna](https://user-images.githubusercontent.com/26578895/56868070-f92aad00-69ed-11e9-8ca9-d5bd0db6e7ea.jpg)

Both version are working using a local moRFeus or contacting remote moRFeus through network using [moRFeus_listener](https://github.com/LamaBleu/moRFeus_listener)

WIP : using pluto as signal generator to replace moRFeus. At this moment I'm not satisfied by first result.

**Comment by LamaBleu** [comment]
Light version : https://github.com/LamaBleu/plutoscripts/tree/master/pluto_power
